#Noah Larbalestier; F006B9P
#Soroush Vosoughi, COSC76 25F
#testing module, contains the paths to the cnf files and the sudoku files as long as in same directory as this file
#partially generated by Cursor Agent (run soolver mechanism to test the solver on the cnf files with different seeds)

import os
from SAT import SAT
#base directory is the directory of the current file
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

CNF_FILES = {
    "one_cell": "one_cell.cnf",
    "all_cells": "all_cells.cnf",
    "rows": "rows.cnf",
    "rows_and_cols": "rows_and_cols.cnf",
    "rules": "rules.cnf",
    "puzzle1": "puzzle1.cnf",
    "puzzle2": "puzzle2.cnf",
    "puzzle_bonus": "puzzle_bonus.cnf",
}

#run the solver on a given cnf file with the given algorithm and parameters
def run_solver(name: str, algo="walksat", max_flips=50000, max_tries=20, p=0.7, seed=None):
    if name not in CNF_FILES:
        raise ValueError(f"Unknown CNF key: {name}")

    cnf_path = os.path.join(BASE_DIR, CNF_FILES[name])
    print(f"\n=== Running {algo.upper()} on {name} ===")
    print(f" CNF: {cnf_path}")
    print(f" max_flips={max_flips}, max_tries={max_tries}, p={p}, seed={seed}")

    solver = SAT(cnf_path)

    if algo == "gsat":
        ok = solver.gsat(
            max_tries=max_tries,
            max_flips=max_flips,
            p_random_move=p,
            seed=seed,
        )
    elif algo == "walksat":
        ok = solver.walksat(
            max_tries=max_tries,
            max_flips=max_flips,
            p_random_move=p,
            seed=seed,
        )
    elif algo == "maxwalksat":
        ok = solver.maxwalksat(
            max_tries=max_tries,
            max_flips=max_flips,
            p_random_move=p,
            seed=seed,
        )
    else:
        raise ValueError(f"Unknown algorithm: {algo}")

    if ok:
        out_path = cnf_path + ".sol"
        solver.write_solution(out_path)
        print(f" Success! Wrote solution to {out_path}")
    else:
        print(" Failed to find a solution.")

if __name__ == "__main__":
    # small exs to test solver behavior:
    run_solver("one_cell")
    run_solver("all_cells")
    run_solver("rows")


    # Uncomment to test harder problems:
    # run_solver("rows_and_cols", max_flips=100000, max_tries=30, p=0.7)
    # run_solver("puzzle1", max_flips=100000, max_tries=50, p=0.7)

    # Example MaxWalkSAT run (optional extra credit experiment):
    run_solver("rows", algo="maxwalksat", max_flips=100000, max_tries=20, p=0.7)
